portfolio_project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from homepage.views import home, about_me


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('about_me/', about_me, name='about'),
    path('projects/', include('projects.urls')),
]

# --> Para que Django sirva los archivos estáticos en modo DEBUG
urlpatterns += static(
    settings.MEDIA_URL,                 # URL de los archivos estáticos
    document_root=settings.MEDIA_ROOT   # Ruta de los archivos estáticos
)

projects/urls.py
from django.urls import path
from projects.views import projects
from .views import project_detail

app_name = 'projects'

urlpatterns = [
    path('', projects, name='projects'),
    path('<int:project_id>/', project_detail, name='project_detail'),
]

homepage/models.py
from django.db import models


# Create your models here.
class Activity(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='activities/images/')

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Description(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='description/images/', blank=True)
    TYPE_CHOICES = (
        ('personal', 'Personal'),
        ('education', 'Education'),
        ('jobs', 'Jobs'),
        ('career', 'Career goals'),
        ('skills', 'Skills'),

    )
    type = models.CharField(max_length=50, choices=TYPE_CHOICES, default='personal')
    company = models.CharField(max_length=100, blank=True)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

projects/models.py
from django.db import models


class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    explanation = models.TextField(blank=True)
    image = models.ImageField(upload_to='projects/images/')
    url = models.URLField(blank=True)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

homepage/views.py
from django.shortcuts import render

from homepage.models import Activity, Description


def home(request):
    # Get all activities
    all_activities = Activity.objects.all()
    return render(request, 'home.html', {'activities': all_activities})


def about_me(request):
    # Get information per type
    personal = Description.objects.filter(type='personal')
    education = Description.objects.filter(type='education')
    jobs = Description.objects.filter(type='jobs')
    skills = Description.objects.filter(type='skills')
    career = Description.objects.filter(type='career')

    for item in jobs:
        print(item.image.url)

    # Create a dictionary with all the information
    info = {
        'educations': education,
        'jobs': jobs,
        'careers': career,
        'skills': skills,
        'personals': personal,
    }

    return render(request, 'about_me.html', info)

projects/views.py
from django.shortcuts import render
from projects.models import Project


# Create your views here.
def projects(request):
    # Obtener todos los proyectos
    all_projects = Project.objects.all()
    return render(request, 'projects/projects.html', {'projects': all_projects})


def project_detail(request, project_id):
    # Get project by ID
    project = Project.objects.get(id=project_id)
    # Get explanations
    explanations = project.explanation.split('\n')
    # Add explanations to project
    project.explanation = explanations
    return render(request, 'projects/project_detail.html', {'project': project})

homepage/templates/about_me.html
{% extends 'layout.html' %}

{% block title %}About me{% endblock %}

{% block content %}
    {% load static %}
    <head>
        <link rel="stylesheet" href="{% static 'css/about.css' %}">
    </head>
    <main>
        <h2>Career path</h2>
        <div>
            {% for personal in personals %}
                <div class="container">
                    <div>
                        <img src="{{ personal.image.url }}" alt="{{ personal.title }}">
                    </div>
                    <div>
                        <h3>{{ personal.title }}</h3>
                        <p>{{ personal.description }}</p>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div>
            {% for education in educations %}
                <div class="container">
                    <div>
                        <img src="{{ education.image.url }}" alt="{{ education.title }}">
                    </div>
                    <div>
                        <h3>{{ education.title }}</h3>
                        <p>{{ education.description }}</p>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div>
            <h2>Professional Experience</h2>
            {% for job in jobs %}
                <div class="work-container">
                    <div>
                        <img src="{{ job.image.url }}" alt="{{ job.title }}">
                    </div>
                    <div>
                        <h3>{{ job.title }}</h3>
                        <p>{{ job.description }}</p>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="skills-container">
            <h2>Skills</h2>
            {% for skill in skills %}
                <ul>
                    <li>{{ skill.title }}</li>
                </ul>
            {% endfor %}
        </div>
        <div>
            <h2>Career goals</h2>
            {% for career in careers %}
                <ul class="container">
                    <li>{{ career.title }}</li>
                </ul>
            {% endfor %}
        </div>
    </main>

{% endblock %}

homepage/templates/home.html
{% extends 'layout.html' %}

{% block title %}Home{% endblock %}

{% block content %}
    {% load static %}
    <head>
        <link rel="stylesheet" href="{% static 'css/home.css' %}">
    </head>
    <main>
        <h1 class="class-name">Uriel Martinez</h1>
        <h2 class="job">Python Developer</h2>
        <p class="content">
            As a Python programming professional, I deeply enjoy the continuous journey of
            learning and discovery. My passion for knowledge drives me to pursue challenging
            and enriching roles, allowing me to leverage and expand my extensive skill set and
            knowledge base. My role as a developer transcends mere code creation; I am dedicated
            to making a meaningful impact, fostering change, and aiding in the development of
            technologies that aim to improve our world.
        </p>
    </main>

    <div class="to-do">
        <div class="title-activity">What I Do</div>
        <div class="show-activities">
            {% for activity in  activities %}
            	<div class="content-activity">
                    <img src="{{ activity.image.url }}">
                    <h3>{{ activity.title }}</h3>
                    <p>{{ activity.description }}</p>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

homepage/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Portfolio - {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/layout.css' %}">
    <link rel="icon" type="image/ico" href="{% static 'icon/python-icon.ico' %}">
</head>
<body>
    <div class="content-wrap">
        <header class="header">
            <nav>
                <ul class="navbar">
                    <li><a href="{% url 'home' %}" class="{% if request.resolver_match.url_name == 'home' %}active{% endif %}">Home</a></li>
                    <li><a href="{% url 'about' %}" class="{% if request.resolver_match.url_name == 'about' %}active{% endif %}">About me</a></li>
                    <li><a href="{% url 'projects:projects' %}" class="{% if request.resolver_match.url_name == 'projects' %}active{% endif %}">Projects</a></li>
                    <li><a href="{% static 'pdf/CV-Python.pdf' %}">CV</a></li>
                    <li><a href="#">Contact</a></li>
                </ul>
            </nav>
        </header>
        <div>
            {% block content %}
            {% endblock %}
        </div>
    </div>

    <footer class="footer">
      <p>&copy; 2024 Portfolio - Django - By Uriel Martinez </p>
    </footer>

</body>
</html>

homepage/templates/projects.html
{% extends 'layout.html' %}

{% block title %}
    Projects
{% endblock %}

{% block content %}
    {% load static %}
    <head>
        <link rel="stylesheet" href="{% static 'css/projects.css' %}" >
    </head>
    <h2>Best projects</h2>
    <div>
        {% for project in projects %}
            <div class="container">
                <h4>
                    {{ project.title }}
                </h4>
                <p>
                    {{ project.description }}
                </p>
                <div>
                    <img src="{{ project.image.url }}" alt="{{ project.title }}">
                </div>
                <p>
                    {{ project.url }}
                </p>
            </div>
        {% endfor %}
    </div>
{% endblock %}

projects/templates/projects/project_detail.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Portfolio - {{ project.title }}</title>
    <link rel="stylesheet" href="{% static 'css/project_detail.css' %}">
</head>
<body>
    <main class="content-wrap">
        <h1>{{ project.title }}</h1>
        <div class="general-container">
            <div class="project-container">
                <img src="{{ project.image.url }}" alt="{{ project.title }}">
                <div>
                    {% for text in project.explanation %}
                    <p>{{ text }}</p>
                    {% endfor %}
                </div>
            </div>
            <div class="link-container">
                <a href="{% url 'projects:projects' %}" class="link-red">Back</a>
                <a href="{{ project.url }}" class="link-blue">View Project</a>
            </div>
        </div>
    </main>
    <footer class="footer">
      <p>&copy; 2024 Portfolio - Django - By Uriel Martinez </p>
    </footer>
</body>
</html>

projects/templates/projects/projects.html
{% extends 'layout.html' %}

{% block title %}
    Projects
{% endblock %}

{% block content %}
    {% load static %}
    <head>
        <link rel="stylesheet" href="{% static 'css/projects.css' %}" >
    </head>
    <h2>Best projects</h2>
    <div>
        {% for project in projects %}
            <div class="container">
                <div>
                    <img src="{{ project.image.url }}" alt="{{ project.title }}">
                </div>
                <h3>{{ project.title }}</h3>
                <p>{{ project.description }}</p>
                <button><a href="{% url 'projects:project_detail' project.id%}">See more</a></button>
            </div>
        {% endfor %}
    </div>
{% endblock %}